Mar-09 18:17:11.287 [main] DEBUG nextflow.cli.Launcher - $> nextflow run prova.nf -profile conda
Mar-09 18:17:11.327 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.10.4
Mar-09 18:17:11.336 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/Users/IEO5505/.nextflow/plugins; core-plugins: nf-amazon@1.11.2,nf-azure@0.14.2,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.4,nf-google@1.4.5,nf-tower@1.5.6,nf-wave@0.5.2
Mar-09 18:17:11.342 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Mar-09 18:17:11.343 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Mar-09 18:17:11.344 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Mar-09 18:17:11.350 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Mar-09 18:17:11.358 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Users/IEO5505/Desktop/MI_TO/three_samples_analyses/nextflow/nextflow.config
Mar-09 18:17:11.358 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/IEO5505/Desktop/MI_TO/three_samples_analyses/nextflow/nextflow.config
Mar-09 18:17:11.370 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `conda`
Mar-09 18:17:11.635 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [conda, singularity, docker]
Mar-09 18:17:11.649 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Mar-09 18:17:11.662 [main] INFO  nextflow.cli.CmdRun - Launching `prova.nf` [high_gilbert] DSL2 - revision: b06065098d
Mar-09 18:17:11.663 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Mar-09 18:17:11.663 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Mar-09 18:17:11.672 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /Users/IEO5505/.nextflow/secrets/store.json
Mar-09 18:17:11.674 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@74174a23] - activable => nextflow.secret.LocalSecretsProvider@74174a23
Mar-09 18:17:11.708 [main] DEBUG nextflow.Session - Session UUID: 67d68f97-a080-4075-8acb-77e98f2ff635
Mar-09 18:17:11.709 [main] DEBUG nextflow.Session - Run name: high_gilbert
Mar-09 18:17:11.709 [main] DEBUG nextflow.Session - Executor pool size: 8
Mar-09 18:17:11.716 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=24; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Mar-09 18:17:11.728 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.10.4 build 5836
  Created: 09-12-2022 09:58 UTC (10:58 CEST)
  System: Mac OS X 11.2.3
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.3+7-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 94482@192.168.1.57 [192.168.1.57]
  CPUs: 8 - Mem: 16 GB (300.8 MB) - Swap: 6 GB (1.2 GB)
Mar-09 18:17:11.735 [main] DEBUG nextflow.Session - Work-dir: /Users/IEO5505/Desktop/MI_TO/three_samples_analyses/nextflow/work [Mac OS X]
Mar-09 18:17:11.735 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /Users/IEO5505/Desktop/MI_TO/three_samples_analyses/nextflow/bin
Mar-09 18:17:11.740 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Mar-09 18:17:11.744 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Mar-09 18:17:11.753 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Mar-09 18:17:11.758 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 9; maxThreads: 1000
Mar-09 18:17:11.791 [main] DEBUG nextflow.Session - Session start
Mar-09 18:17:11.910 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-09 18:17:11.951 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-09 18:17:11.951 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-09 18:17:11.955 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Mar-09 18:17:11.957 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=16 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Mar-09 18:17:12.007 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: foo
Mar-09 18:17:12.007 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Mar-09 18:17:12.010 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > foo
Mar-09 18:17:12.011 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Mar-09 18:17:12.011 [main] DEBUG nextflow.Session - Session await
Mar-09 18:17:12.087 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-09 18:17:12.088 [Task submitter] INFO  nextflow.Session - [68/44df93] Submitted process > foo (1)
Mar-09 18:17:12.146 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: foo (1); status: COMPLETED; exit: 1; error: -; workDir: /Users/IEO5505/Desktop/MI_TO/three_samples_analyses/nextflow/work/68/44df9368274178a08d3146cf7fc898]
Mar-09 18:17:12.154 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'foo (1)'

Caused by:
  Process `foo (1)` terminated with an error exit status (1)

Command executed:

  #!/usr/bin/python 
  import scanpy as sc
  print('Hello world!')

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File ".command.sh", line 2, in <module>
      import scanpy as sc
  ImportError: No module named scanpy

Work dir:
  /Users/IEO5505/Desktop/MI_TO/three_samples_analyses/nextflow/work/68/44df9368274178a08d3146cf7fc898

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
Mar-09 18:17:12.158 [main] DEBUG nextflow.Session - Session await > all processes finished
Mar-09 18:17:12.158 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `foo (1)` terminated with an error exit status (1)
Mar-09 18:17:12.163 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-09 18:17:12.166 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=1; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=8ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Mar-09 18:17:12.369 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Mar-09 18:17:12.380 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
